// const AUTH_STATUS = 'AUTH_STATUS'
// const ADMIN_STATUS = 'ADMIN_STATUS'
const SET_ADMIN_DATA = 'SET_ADMIN_DATA'
const SET_USERS = 'SET_USERS'
const SET_ADMINS = 'SET_ADMINS'
const SELECT_USER_FOR_BULK_ACTION = 'SELECT_USER_FOR_BULK_ACTION'
const DESELECT_USER_FOR_BULK_ACTION = 'DESELECT_USER_FOR_BULK_ACTION'
const CLEAR_SELECTED_USERS_FOR_BULK_ACTION = 'CLEAR_SELECTED_USERS_FOR_BULK_ACTION'
const SELECT_ADMIN_FOR_BULK_ACTION = 'SELECT_ADMIN_FOR_BULK_ACTION'
const DESELECT_ADMIN_FOR_BULK_ACTION = 'DESELECT_ADMIN_FOR_BULK_ACTION'
const CLEAR_SELECTED_ADMINS_FOR_BULK_ACTION = 'CLEAR_SELECTED_ADMINS_FOR_BULK_ACTION'

export {
  // AUTH_STATUS,
  // ADMIN_STATUS,
  SET_ADMIN_DATA,
  SET_USERS,
  SET_ADMINS,
  DESELECT_USER_FOR_BULK_ACTION,
  SELECT_USER_FOR_BULK_ACTION,
  CLEAR_SELECTED_USERS_FOR_BULK_ACTION,
  DESELECT_ADMIN_FOR_BULK_ACTION,
  SELECT_ADMIN_FOR_BULK_ACTION,
  CLEAR_SELECTED_ADMINS_FOR_BULK_ACTION,
}
