// CMS - USER MANAGEMENT
const SET_ADMIN_DATA = 'SET_ADMIN_DATA'
const SET_APP_USER_DATA = 'SET_APP_USER_DATA'
const SET_USERS = 'SET_USERS'
const SET_ADMINS = 'SET_ADMINS'
const SELECT_USER_FOR_BULK_ACTION = 'SELECT_USER_FOR_BULK_ACTION'
const DESELECT_USER_FOR_BULK_ACTION = 'DESELECT_USER_FOR_BULK_ACTION'
const CLEAR_SELECTED_USERS_FOR_BULK_ACTION = 'CLEAR_SELECTED_USERS_FOR_BULK_ACTION'
const SELECT_ADMIN_FOR_BULK_ACTION = 'SELECT_ADMIN_FOR_BULK_ACTION'
const DESELECT_ADMIN_FOR_BULK_ACTION = 'DESELECT_ADMIN_FOR_BULK_ACTION'
const CLEAR_SELECTED_ADMINS_FOR_BULK_ACTION = 'CLEAR_SELECTED_ADMINS_FOR_BULK_ACTION'
const SHOW_USER_EDIT_VIEW = 'SHOW_USER_EDIT_VIEW'
const HIDE_USER_EDIT_VIEW = 'HIDE_USER_EDIT_VIEW'
const SET_SELECTED_USER_FOR_EDITING = 'SET_SELECTED_USER_FOR_EDITING'
const SET_SELECTED_ADMIN_FOR_EDITING = 'SET_SELECTED_ADMIN_FOR_EDITING'
// ECO LAB APP
// const SAVE_WEB_MODULE = 'SAVE_WEB_MODULE'
const SAVING_WEB_MODULE = 'SAVING_WEB_MODULE'
const WEB_MODULE_SAVED = 'WEB_MODULE_SAVED'
const GETTING_WEB_MODULES = 'GETTING_WEB_MODULES'
const SET_WEB_MODULES = 'SET_WEB_MODULES'
const DELETING_WEB_MODULE = 'DELETING_WEB_MODULE'
const WEB_MODULE_DELETED = 'WEB_MODULE_DELETED'

export {
  // CMS
  SET_USERS,
  SET_ADMINS,
  SET_ADMIN_DATA,
  SET_APP_USER_DATA,
  SELECT_USER_FOR_BULK_ACTION,
  DESELECT_USER_FOR_BULK_ACTION,
  CLEAR_SELECTED_USERS_FOR_BULK_ACTION,
  DESELECT_ADMIN_FOR_BULK_ACTION,
  SELECT_ADMIN_FOR_BULK_ACTION,
  CLEAR_SELECTED_ADMINS_FOR_BULK_ACTION,
  SHOW_USER_EDIT_VIEW,
  HIDE_USER_EDIT_VIEW,
  SET_SELECTED_USER_FOR_EDITING,
  SET_SELECTED_ADMIN_FOR_EDITING,
  // ECO LAB
  // SAVE_WEB_MODULE,
  SAVING_WEB_MODULE,
  WEB_MODULE_SAVED,
  GETTING_WEB_MODULES,
  SET_WEB_MODULES,
  DELETING_WEB_MODULE,
  WEB_MODULE_DELETED,

}
