// const AUTH_STATUS = 'AUTH_STATUS'
// const ADMIN_STATUS = 'ADMIN_STATUS'
const USER_DATA = 'USER_DATA'
const SET_USERS = 'SET_USERS'
const SELECT_USER_FOR_BULK_ACTION = 'SELECT_USER_FOR_BULK_ACTION'
const DESELECT_USER_FOR_BULK_ACTION = 'DESELECT_USER_FOR_BULK_ACTION'
const CLEAR_SELECTED_USERS_FOR_BULK_ACTION = 'CLEAR_SELECTED_USERS_FOR_BULK_ACTION'

export {
  // AUTH_STATUS,
  // ADMIN_STATUS,
  USER_DATA,
  SET_USERS,
  DESELECT_USER_FOR_BULK_ACTION,
  SELECT_USER_FOR_BULK_ACTION,
  CLEAR_SELECTED_USERS_FOR_BULK_ACTION,
}
